blueprint:
  name: Dimming Light with Button Press
  description: Control a light with a button press.
  domain: automation
  input:
    button_entity:
      name: Button
      description: The button entity to use.
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: Light
      description: The light entity to control.
      selector:
        entity:
          domain: light

trigger:
  platform: state
  entity_id: !input "button_entity"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'pressed' and (trigger.from_state.last_changed - trigger.to_state.last_changed).total_seconds() < 0.5 }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input "light_entity"
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'pressed' }}"
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input "button_entity"
                  state: "pressed"
              sequence:
                - repeat:
                    count: 20
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: !input "light_entity"
                        data:
                          brightness_step_pct: 5
                      - delay:
                          milliseconds: 300
                - repeat:
                    count: 20
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: !input "light_entity"
                        data:
                          brightness_step_pct: -5
                      - delay:
                          milliseconds: 300
